export const ALL_BLOG_REQUEST = "ALL_BLOG_REQUEST";
export const ALL_BLOG_SUCCESS = "ALL_BLOG_SUCCESS";
export const ALL_BLOG_FAIL = "ALL_BLOG_FAIL";

export const ALL_BLOG_REQUEST_ADMIN = "ALL_BLOG_REQUEST_ADMIN";
export const ALL_BLOG_SUCCESS_ADMIN = "ALL_BLOG_SUCCESS_ADMIN";
export const ALL_BLOG_FAIL_ADMIN = "ALL_BLOG_FAIL_ADMIN";

export const BLOG_DETAILS_REQUEST = "BLOG_DETAILS_REQUEST";
export const BLOG_DETAILS_SUCCESS = "BLOG_DETAILS_SUCCESS";
export const BLOG_DETAILS_FAIL = "BLOG_DETAILS_FAIL";

export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_RESET = "CREATE_BLOG_RESET";
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";

export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_RESET = "UPDATE_BLOG_RESET";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";

export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_RESET = "DELETE_BLOG_RESET";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
