export const ALL_COMPANY_REQUEST = "ALL_COMPANY_REQUEST";
export const ALL_COMPANY_SUCCESS = "ALL_COMPANY_SUCCESS";
export const ALL_COMPANY_FAIL = "ALL_COMPANY_FAIL";

export const ALL_COMPANY_REQUEST_ADMIN = "ALL_COMPANY_REQUEST_ADMIN";
export const ALL_COMPANY_SUCCESS_ADMIN = "ALL_COMPANY_SUCCESS_ADMIN";
export const ALL_COMPANY_FAIL_ADMIN = "ALL_COMPANY_FAIL_ADMIN";

export const COMPANY_DETAILS_REQUEST = "COMPANY_DETAILS_REQUEST";
export const COMPANY_DETAILS_SUCCESS = "COMPANY_DETAILS_SUCCESS";
export const COMPANY_DETAILS_FAIL = "COMPANY_DETAILS_FAIL";

export const CREATE_COMPANY_REQUEST = "CREATE_COMPANY_REQUEST";
export const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS";
export const CREATE_COMPANY_RESET = "CREATE_COMPANY_RESET";
export const CREATE_COMPANY_FAIL = "CREATE_COMPANY_FAIL";

export const UPDATE_COMPANY_REQUEST = "UPDATE_COMPANY_REQUEST";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_RESET = "UPDATE_COMPANY_RESET";
export const UPDATE_COMPANY_FAIL = "UPDATE_COMPANY_FAIL";

export const DELETE_COMPANY_REQUEST = "DELETE_COMPANY_REQUEST";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_RESET = "DELETE_COMPANY_RESET";
export const DELETE_COMPANY_FAIL = "DELETE_COMPANY_FAIL";




export const CLEAR_ERRORS = "CLEAR_ERRORS";
