export const ALL_EVENT_REQUEST = "ALL_EVENT_REQUEST";
export const ALL_EVENT_SUCCESS = "ALL_EVENT_SUCCESS";
export const ALL_EVENT_FAIL = "ALL_EVENT_FAIL";

export const ALL_EVENT_REQUEST_ADMIN = "ALL_EVENT_REQUEST_ADMIN";
export const ALL_EVENT_SUCCESS_ADMIN = "ALL_EVENT_SUCCESS_ADMIN";
export const ALL_EVENT_FAIL_ADMIN = "ALL_EVENT_FAIL_ADMIN";

export const EVENT_DETAILS_REQUEST = "EVENT_DETAILS_REQUEST";
export const EVENT_DETAILS_SUCCESS = "EVENT_DETAILS_SUCCESS";
export const EVENT_DETAILS_FAIL = "EVENT_DETAILS_FAIL";

export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_RESET = "CREATE_EVENT_RESET";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";

export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_RESET = "UPDATE_EVENT_RESET";
export const UPDATE_EVENT_FAIL = "UPDATE_EVENT_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_RESET = "DELETE_EVENT_RESET";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
