export const ALL_MENU_REQUEST = "ALL_MENU_REQUEST";
export const ALL_MENU_SUCCESS = "ALL_MENU_SUCCESS";
export const ALL_MENU_FAIL = "ALL_MENU_FAIL";


export const ALL_MENU_REQUEST_ADMIN = "ALL_MENU_REQUEST_ADMIN";
export const ALL_MENU_SUCCESS_ADMIN = "ALL_MENU_SUCCESS_ADMIN";
export const ALL_MENU_FAIL_ADMIN = "ALL_MENU_FAIL_ADMIN";

export const MENU_DETAILS_REQUEST = "MENU_DETAILS_REQUEST";
export const MENU_DETAILS_SUCCESS = "MENU_DETAILS_SUCCESS";
export const MENU_DETAILS_FAIL = "MENU_DETAILS_FAIL";

export const CREATE_MENU_REQUEST = "CREATE_MENU_REQUEST";
export const CREATE_MENU_SUCCESS = "CREATE_MENU_SUCCESS";
export const CREATE_MENU_RESET = "CREATE_MENU_RESET";
export const CREATE_MENU_FAIL = "CREATE_MENU_FAIL";

export const UPDATE_MENU_REQUEST = "UPDATE_MENU_REQUEST";
export const UPDATE_MENU_SUCCESS = "UPDATE_MENU_SUCCESS";
export const UPDATE_MENU_RESET = "UPDATE_MENU_RESET";
export const UPDATE_MENU_FAIL = "UPDATE_MENU_FAIL";

export const DELETE_MENU_REQUEST = "DELETE_MENU_REQUEST";
export const DELETE_MENU_SUCCESS = "DELETE_MENU_SUCCESS";
export const DELETE_MENU_RESET = "DELETE_MENU_RESET";
export const DELETE_MENU_FAIL = "DELETE_MENU_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
